//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Scooters
    {
        public int ID_Orders_Scooters { get; set; }
        public int Order_ID { get; set; }
        public int Scooter_ID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Scooters Scooters { get; set; }
    }
}
