//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storages
    {
        public int ID_Storage { get; set; }
        public int Scooter_ID { get; set; }
        public int Scooter_Quantity { get; set; }
        public int Provider_ID { get; set; }
    
        public virtual Providers Providers { get; set; }
        public virtual Scooters Scooters { get; set; }
    }
}
